language: python
python:
  - "3.4"
  - "3.5"
env:
  global:
    - DJANGO_SETTINGS_MODULE=settings.test
install: "pip install -r requirements_test.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: py.test . -m "not veryslow" --nomigrations --cov="." --cov-report="term-missing"
after_script: pip install coveralls && coveralls
