language: python
python:
  - "3.4"
  - "3.5"
env:
  global:
    - DJANGO_SETTINGS_MODULE=settings.test
install: "pip install -r requirements_test.txt"
script: xvfb-run -a py.test . -m "not veryslow" --nomigrations --cov="." --cov-report="term-missing"
after_script: pip install coveralls && coveralls
