db:
  image: postgres
broker:
  image: rabbitmq
cache:
  image: memcached
assets:
  build: ./apostello/assets/
  command: npm run watch
  volumes:
    - .:/code
celery:
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: settings.docker
    C_FORCE_ROOT: 'True'
  command: ./manage.py celery worker -E -B -l info --concurrency=1
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
    - broker
    - cache
web:
  build: .
  environment:
    DJANGO_SETTINGS_MODULE: settings.docker
  command: bash -c "sleep 3 && ./manage.py runserver 0.0.0.0:8000"
  volumes:
    - .:/code
  ports:
    - "4000:8000"
  links:
    - celery 
    - db
    - broker
    - cache
