---

server_root_dir: /webapps
setup_camera: no

virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_path: "{{ project_path }}"

celery_user: "{{ application_name }}"
celery_group: webapps

celery_application_name: celery
celerycam_application_name: celerycam
celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"
celery_template_file: "{{ celery_application_name }}_start.j2"
celerycam_template_file: "{{ celerycam_application_name }}_start.j2"

# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
