---

- name: Create the folder for the django_q scripts
  file: path={{ django_q_scripts_dir }}
        owner={{ django_q_user }}
        group={{ django_q_group }}
        mode=0774
        state=directory
  tags:
    - django_q

- name: Create the {{ django_q_application_name }} script file
  template: src={{ django_q_template_file }}
            dest={{ django_q_scripts_dir }}/{{ django_q_application_name }}_start
            owner={{ django_q_user }}
            group={{ django_q_group }}
            mode=0755
  tags:
    - django_q
