---

- name: Setup the Git repo
  git: repo={{ git_repo }} dest={{ project_path }} accept_hostkey=yes version={{git_version}}
  when: setup_git_repo
  tags: git

- name: register opbeat release
  shell: 'cd {{ application_path }} && curl https://intake.opbeat.com/api/v1/organizations/{{ opbeat_organization_id }}/apps/{{ opbeat_app_id }}/releases/ -H "Authorization: Bearer {{ opbeat_secret_token }}" -d rev=`git log -n 1 --pretty=format:%H` -d branch=`git rev-parse --abbrev-ref HEAD` -d status=completed'
