---

- name: Setup the Git repo
  git: repo={{ git_repo }} dest={{ project_path }} accept_hostkey=yes version={{git_version}}
  when: setup_git_repo
  tags: git

- name: Tell rollbar about deployment
  when: 'rollbar_access_token|length > 0'
  rollbar_deployment:
    token: '{{ rollbar_access_token }}'
    environment: production
    user: ansible
    revision: '{{ git_version }}'
